services:
  laravel:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /var/www/html/storage
      - /var/www/html/bootstrap/cache 
      - /var/www/html/vendor
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_web
    restart: unless-stopped
    ports:
      - '172.20.8.179:80:80'
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
